export const englishText = {
    menuDesktop1: "About",
    menuDesktop2: "Services",
    menuDesktop3: "Projects",
    menuDesktop4: "Contact",
    menuMobile1: "About",
    menuMobile2: "Services",
    menuMobile3: "Projects",
    menuMobile4: "Contact",
    formTitle: "Contact",
    formName: " Name",
    formMessage: " Message",
    submitButton:"Send",
    title: "We are creatives",
    boxTitle1 : "Transform your brand",
    boxText1 : "We are a full-service creative agency specializing in helping brands grow fast. Engage your clients through compelling visuals that do most of the marketing for you.",
    learn1: "Learn more",
    boxTitle4 : "Stand out to the right audience",
    boxText4 : "Using a collaborative formula of designers, researchers, photographers, videographers, and copywriters, we'll build and extend your brand in digital places.",
    learn4: "Learn more",
    boxTitle5 : "Graphic Design",
    boxText5 : "Great design makes you memorable. We deliver artwork that underscores your brand message and captures potential clients’ attention.",
    boxTitle6 : "Photography",
    boxText6 : "Increase your credibility by getting the most stunning, high-quality photos that improve your business image.",
    testimonialTitle: "Client Testimonials",
    clientText1: "We put our trust in Sunnyside and they delivered, making sure our needs were met and deadlines were always hit.",
    clientOccupation1: "Marketing Director",
    clientText2: "Sunnyside’s enthusiasm coupled with their keen interest in our brand’s success made it a satisfying and enjoyable experience.",
    clientOccupation2: "Chief Operating Officer",
    clientText3: "Incredible end result! Our sales increased over 400% when we worked with Sunnyside. Highly recommended!",
    clientOccupation3: "Business Owner",
    menuFooter1: "About",
    menuFooter2: "Services",
    menuFooter3: "Projects"
}