export const portugueseText = {
    menuDesktop1: "Sobre",
    menuDesktop2: "Serviços",
    menuDesktop3: "Projetos",
    menuDesktop4: "Contato",
    menuMobile1: "Sobre",
    menuMobile2: "Serviços",
    menuMobile3: "Projetos",
    menuMobile4: "Contato",
    formTitle: "Contato",
    formName: " Nome",
    formMessage: " Menssagem",
    submitButton:"Enviar",
    alertName:'⚠ Digite seu nome',
    alertEmail:'⚠ Esse e-mail não parece válido',
    alertMessage:'⚠ Digite uma mensagem',
    emailSent:"✔ Seu e-mail foi enviado!",
    title: "Somos Criativos!",
    boxTitle1 : "Transforme sua marca",
    boxText1 : "Somos uma agência especializada em ajudar as marcas a crescerem rapidamente. Engage seus clientes por meio de recursos visuais atraentes que farão a maior parte do marketing para você.",
    learn1: "Saiba mais",
    boxTitle4 : "Destaque-se para o público certo",
    boxText4 : "Contando com uma excelente equipe de designers, pesquisadores, fotógrafos, cinegrafistas e redatores, ampliaremos sua marca na internet.",
    learn4: "Saiba mais",
    boxTitle5 : "Design Gráfico",
    boxText5 : "Um ótimo design torna você memorável. Entregamos obras de arte que ressaltam a mensagem da sua marca e capturam a atenção de clientes em potencial.",
    boxTitle6 : "Fotografia",
    boxText6 : "Aumente sua credibilidade com imagens impressionantes e de alta qualidade, que irão valorizar ainda mais a imagem da sua empresa.",
    testimonialTitle: "Depoiementos de Clientes",
    clientText1: "Confiamos na Sunnyside e eles entregaram, garantindo que nossas necessidades fossem atendidas dentro do prazo.",
    clientOccupation1: "Diretora de Marketing",
    clientText2: "O entusiasmo de Sunnyside, e seu grande interesse no sucesso da nossa marca, tornou isso uma experiência maravilhosa.",
    clientOccupation2: "Diretor de Operações",
    clientText3: "Resultado final incrível! Nossas vendas aumentaram mais de 400% quando trabalhamos com a Sunnyside!",
    clientOccupation3: "Empresária",
    menuFooter1: "Sobre",
    menuFooter2: "Serviços",
    menuFooter3: "Projetos"
}